# Naive Bayes Classification - Diabetes Dataset

Tugas Machine Learning

Nama : Ali Akbar Bermano
NPM: G1A024041
Metode : Naive Bayes  
Dataset : diabetes.csv

import library

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

Mount drive

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Cek isi drive

In [6]:
!ls /content/drive/MyDrive

 16285991472532945197677496920095.jpg
 16285992569838900097044785282701.jpg
 16285993313501132899212429543543.jpg
 20241023092047000261-1729693286700.jpg
'Ali akbar bermano_G1A024041'
'ali akbar bermano_G1A024041.docx'
'Ali Akbar Bermano_ G1A024041_FormRegPKKFT24.pdf'
'ali akbar bermano_G1A024041.gdoc'
'Ali Akbar Bermano_G1A024041_KALKULUS.pptx'
'Ali akbar bermano_G1A024041_MSI-1.docx'
'Ali akbar bermano_G1A024041_MSI-1.pdf'
'Ali akbar bermano_G1A024041_RESUME JURNAL FISIKA (1).pdf'
'Ali Akbar Bermano_G1A024041_TI A.pdf'
'ALI AKBAR BERMANO (NPM: G1A024041) '
'[Bakadame.com] Overlord Volume 12 - The paladin of Holy Kingdom (1).pdf'
'[Bakadame.com] Overlord Volume 12 - The paladin of Holy Kingdom.pdf'
'[Bakadame.com] Overlord Volume 13 - The paladin of Holy Kingdom (1).pdf'
'[Bakadame.com] Overlord Volume 13 - The paladin of Holy Kingdom.pdf'
'-Bakadame.com- Overlord Volume 9 - The Magic Caster Of Destroy (1).pdf'
'-Bakadame.com- Overlord Volume 9 - The Magic Caster Of Destroy.pdf'
'Buku fiksi dan nonfiksi ali akbar.docx'
 CamScanner11-11-202410.21.pdf
'CamScanner 11-12-2024 17.55.pdf'
 Classroom
'Colab Notebooks'
 diabetes.csv
 dowload
'Fix - Renna - Pengantar Sistem Multimedia.gdoc'
'Formulir tanpa judul (1).gform'
'Formulir tanpa judul (2).gform'
'Formulir tanpa judul (3).gform'
'Formulir tanpa judul (4).gform'
'Formulir tanpa judul.gform'
'Formulir tanpa judul (Jawaban) (1).gsheet'
'Formulir tanpa judul (Jawaban).gsheet'
'foto kegiatan pokja 4'
'Fungsi dan Peran Sumber Daya Alam dalam Pembangunan Ekonomi ali akbar bremano.docx'
'G1A024041_ali akbar bermano_artikel method java.pdf'
'Halal Dan Haram materi ali akbar bermano.docx'
 IMG_20200324_084134.jpg
 IMG_20200326_201033.jpg
 IMG_20200328_071803.jpg
'IMG_20200330_212230 (1).jpg'
 IMG_20200330_212230.jpg
 IMG_20201016_132610.jpg
 IMG_20201023_131812.jpg
 IMG_20220125_192718.jpg
 IMG_20220125_194337.jpg
 IMG_20220125_194342.jpg
 IMG_20220125_195427.jpg
 IMG-20240613-WA0006.jpg
 IMG_20240615_181819.jpg
 IMG_20240717_111333.jpg
 IMG_20250304_084238.jpg
 IMG_20250304_095605.jpg
 IMG_20251125_115455.jpg
'Informasi Kontak (1).gform'
'Informasi Kontak.gform'
'Informasi Kontak (Jawaban).gsheet'
'Introduction to Multimedia Systems (Gaurav Bhatnagar) (z-lib.org).gdoc'
'JFo_5_Practice (1).gdoc'
'JFo_5_Practice (2).gdoc'
 JFo_5_Practice.gdoc
'JFo_Section_4_Student.zip (Unzipped Files)'
'Keberagaman dalam masyarakat Indonesia ALI AKBAR BERMANO VIII H.docx'
'kelas A_G1A024041_Ali Akbar Bermano.pdf'
 LAPRAK4.gdoc
'lpj sekum 2025_merged.pdf'
'MR ALI AKBAR BERMANO.pdf'
'Overlord 10 indo (1).pdf'
'Overlord 10 indo.pdf'
'Overlord 14 indo (1).pdf'
'Overlord 14 indo.pdf'
'Overlord - Blu-ray Special 1 - Emissary of the King (1).pdf'
'Overlord - Blu-ray Special 1 - Emissary of the King.pdf'
'Overlord - Blu-ray Special 4 - Prologue 1st Half.pdf'
'Overlord Vampire Princess of the Lost Country (1).pdf'
'Overlord Vampire Princess of the Lost Country.pdf'
'Overlord Vol. 01 - The Undead King (1).pdf'
'Overlord Vol. 01 - The Undead King.pdf'
'Overlord Vol. 02 - The Dark Warrior (1).pdf'
'Overlord Vol. 02 - The Dark Warrior.pdf'
'Overlord Vol. 03 - The Blood Valkyrie-1 (1).pdf'
'Overlord Vol. 03 - The Blood Valkyrie-1.pdf'
'Overlord Vol. 04 - Lizardman Heroes (1).pdf'
'Overlord Vol. 04 - Lizardman Heroes.pdf'
'Overlord Vol. 07 - The Invaders Of The Large Tomb (1).pdf'
'Overlord Vol. 07 - The Invaders Of The Large Tomb.pdf'
'Overlord Vol. 08 - The Two Leaders (1).pdf'
'Overlord Vol. 08 - The Two Leaders.pdf'
'Overlord Vol. 09 - The Magic Caster Of Destroy (1).pdf'
'Overlord Vol. 09 - The Magic Caster Of Destroy.pdf'
'Overlord Vol. 11 - The Craftsman of Dwarf (1).pdf'
'Overlord Vol. 11 - The Craftsman of Dwarf.pdf'
'Overlord Volume 15 - The Half-Elf God-kin Part I bahasa indonesia.pdf'
 PPC00434.JPG
 Screenshot_20231202-134028.png
 Screenshot_2024-06-13-15-02-00-694_com.android.chrome.jpg
 Screenshot_2024-10-27-13-24-01-684_com.instagram.android.jpg
 Screenshot_2024-10-27-13-24-08-320_com.instagram.android.jpg
 Screenshot_2025-01-21-08-39-10-298_com.google.android.gm.jpg
 Screenshot_2025-04-30-15-28-41-771_id.bni.wondr.jpg
 Screenshot_2025-11-15-18-12-10-958_id.bni.wondr.jpg
 sda
'sistem eksresi pada manusia ali akbar.docx'
'suara project 1'
 template.gdoc
 TUBES
"tugas meringkas sbk , 'membuat poster' ali akbar bermano.docx"
 VID_20250423_155755.mp4

load dataset

In [7]:
import pandas as pd

path = "/content/drive/MyDrive/diabetes.csv"

data = pd.read_csv(path)

data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

eksplorasi data

In [9]:
data.shape

(768, 9)

In [10]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [11]:
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

In [12]:
data["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [13]:
data["Outcome"].value_counts(normalize=True)

Outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

Split Data (Membagi Data Training dan Testing)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Training Model Naive Bayes

In [15]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

In [17]:
y_pred = model.predict(X_test)

menghitung mean

In [18]:
import pandas as pd

mean = X_train.groupby(y_train).mean()

mean

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.241895,110.214464,68.309227,19.748130,72.254364,30.256608,0.431254,30.556110
1,4.685446,140.887324,71.497653,21.624413,98.727700,35.234272,0.540545,37.333333

mengambil variance

In [19]:
variance = X_train.groupby(y_train).var()

variance

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,9.158840,678.328890,312.044140,212.618903,10233.220137,56.834362,0.094310,122.837469
1,13.093985,1070.185357,395.534193,285.301665,19298.010408,49.758584,0.142307,120.723270

mengambil data test

In [20]:
X_test.iloc[0]

Pregnancies                   6.00
Glucose                      98.00
BloodPressure                58.00
SkinThickness                33.00
Insulin                     190.00
BMI                          34.00
DiabetesPedigreeFunction      0.43
Age                          43.00
Name: 668, dtype: float64

Accuracy Score / Evaluasi Model.

In [21]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7662337662337663

In [1]:
import pandas as pd

hasil = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

hasil.head()

NameError: name 'y_test' is not defined

Model Naive Bayes digunakan untuk melakukan klasifikasi pada dataset diabetes.

Dataset dibagi menjadi data training dan testing dengan perbandingan 80:20.

Berdasarkan hasil evaluasi menggunakan accuracy score, model memiliki tingkat akurasi sekitar 0.77 atau 77%.

Hal ini menunjukkan bahwa model dapat memprediksi kemungkinan diabetes dengan cukup baik.